### ISSUE TITLE
Can not compile project

### ISSUE THREAD

**Issue by smartum-ks** [zapproject/Zap-monorepo#6]
> lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "@zap/arbiter", "@zap/artifacts", "@zap/basecontract", "@zap/bondage", "@zap/curve", "@zap/dispatch", "@zap/provider", "@zap/registry", "@zap/subscriber", "@zap/utils", "@zap/zaptoken"
> src/migrations/constants.ts:1:21 - error TS2307: Cannot find module '@zap/curve'.
> 
> 1 import {Curve} from "@zap/curve"
>                       ~~~~~~~~~~~~
> src/types.ts:1:21 - error TS2307: Cannot find module '@zap/curve'.
> 1 import {Curve} from "@zap/curve";
>                       ~~~~~~~~~~~~
> lerna ERR! exec Errored while executing 'tsc' in '@zap/utils'

**Comment by propulsor** [comment]
Fixed  with correct package.json files
